<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'This site is down for maintenance.<br />Please check back again soon.';
	public $display_offline_message = '1';
	public $offline_image = '';
	public $sitename = '5Square';
	public $editor = 'jce';
	public $captcha = '0';
	public $list_limit = '20';
	public $access = '1';
	public $debug = '0';
	public $debug_lang = '0';
	public $dbtype = 'mysqli';
	public $host = 'localhost';
	public $user = 'squaress_live15';
	public $password = 'R%y!,(0Ry0=5';
	public $db = 'squaress_live15';
	public $dbprefix = 'jl07r_';
	public $live_site = '';
	public $secret = 'V3EYgQ199hgUM8uw';
	public $gzip = '0';
	public $error_reporting = 'simple';
	public $helpurl = 'https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '';
	public $ftp_port = '';
	public $ftp_user = '';
	public $ftp_pass = '';
	public $ftp_root = '';
	public $ftp_enable = '0';
	public $offset = 'UTC';
	public $mailonline = '1';
	public $mailer = 'smtp';
	public $mailfrom = 'DO_NOT_REPLY@5squaresstudio.com';
	public $fromname = '5Square';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '1';
	public $smtpuser = 'mailer@futureworkz.com';
	public $smtppass = '%L8=aKby';
	public $smtphost = 'smtp.gmail.com';
	public $smtpsecure = 'ssl';
	public $smtpport = '465';
	public $caching = '0';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $MetaDesc = ':: 5 Squares Studio ::  Work : Contact : About us
:: 5 ::  Brand :: Business Strategy :: Product Design ...
';
	public $MetaKeys = ':: 5 Squares Studio ::  Work : Contact : About us
Brand, Strategy, Design, Photography, Prototype, 5 Things';
	public $MetaTitle = '1';
	public $MetaAuthor = '1';
	public $MetaVersion = '0';
	public $robots = '';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $unicodeslugs = '0';
	public $feed_limit = '10';
	public $log_path = '/home/squaress/public_html/logs';
	public $tmp_path = '/home/squaress/public_html/tmp';
	public $lifetime = '999';
	public $session_handler = 'database';
	public $memcache_persist = '1';
	public $memcache_compress = '0';
	public $memcache_server_host = 'localhost';
	public $memcache_server_port = '11211';
	public $memcached_persist = '1';
	public $memcached_compress = '0';
	public $memcached_server_host = 'localhost';
	public $memcached_server_port = '11211';
	public $redis_persist = '1';
	public $redis_server_host = 'localhost';
	public $redis_server_port = '6379';
	public $redis_server_auth = '';
	public $redis_server_db = '0';
	public $proxy_enable = '0';
	public $proxy_host = '';
	public $proxy_port = '';
	public $proxy_user = '';
	public $proxy_pass = '';
	public $massmailoff = '0';
	public $MetaRights = '';
	public $sitename_pagetitles = '0';
	public $force_ssl = '0';
	public $session_memcache_server_host = 'localhost';
	public $session_memcache_server_port = '11211';
	public $session_memcached_server_host = 'localhost';
	public $session_memcached_server_port = '11211';
	public $frontediting = '1';
	public $feed_email = 'author';
	public $cookie_domain = '';
	public $cookie_path = '';
	public $asset_id = '1';
}